{
 "title": "Website Monitor",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "All UP/DOWN Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status of All Websites",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{instance=\"http://angulosolido.pt/\",job=\"blackbox\",module=\"http_2xx\"}) and count(probe_success{instance=\"https://nextcloud.miguelndecarvalho.pt/\",job=\"blackbox\",module=\"https_2xx\"})"
    }
   ]
  },
  {
   "title": "Website Monitor",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "probe_success{}\t", "legendFormat": "{{instance}} status" }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "probe_duration_seconds{}", "legendFormat": "{{instance}} (s)" }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{}\t",
     "legendFormat": "{{instance}} (s)"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 16 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "avg(probe_duration_seconds{})" }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 16 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{})"
    }
   ]
  },
  {
   "title": "Nextcloud Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "https://nextcloud.miguelndecarvalho.pt",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_success{instance=\"https://nextcloud.miguelndecarvalho.pt/\",job=\"blackbox\",module=\"https_2xx\"}\t"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 21 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_ssl{instance=\"https://nextcloud.miguelndecarvalho.pt/\",job=\"blackbox\",module=\"https_2xx\"}\t"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=\"https://nextcloud.miguelndecarvalho.pt/\",job=\"blackbox\",module=\"https_2xx\"}\t",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "DNS Lookup",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_dns_lookup_time_seconds{instance=\"https://nextcloud.miguelndecarvalho.pt/\",job=\"blackbox\",module=\"https_2xx\"}\t",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "SSL Cert Expiry",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 23 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{instance=\"https://nextcloud.miguelndecarvalho.pt/\",job=\"blackbox\",module=\"https_2xx\"}-time()"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_status_code{instance=\"https://nextcloud.miguelndecarvalho.pt/\",job=\"blackbox\",module=\"https_2xx\"}\t"
      }
     ]
    },
    {
     "title": "Average Probe Duration",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 27 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=\"https://nextcloud.miguelndecarvalho.pt/\",job=\"blackbox\",module=\"https_2xx\"}\t)"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 27 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_dns_lookup_time_seconds{instance=\"https://nextcloud.miguelndecarvalho.pt/\",job=\"blackbox\",module=\"https_2xx\"}\t)"
      }
     ]
    }
   ]
  },
  {
   "title": "AnguloSolido Website",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "http://angulosolido.pt/",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_success{instance=\"http://angulosolido.pt/\",job=\"blackbox\",module=\"http_2xx\"}\t"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_ssl{instance=\"http://nextcloud.miguelndecarvalho.pt/\",job=\"blackbox\",module=\"http_2xx\"}\t"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=\"http://angulosolido.pt/\",job=\"blackbox\",module=\"http_2xx\"}\t",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "DNS Lookup",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_dns_lookup_time_seconds{instance=\"http://angulosolido.pt/\",job=\"blackbox\",module=\"http_2xx\"}\t",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "SSL Cert Expiry",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 24 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{instance=\"http://angulosolido.pt/\",job=\"blackbox\",module=\"https_2xx\"}-time()"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_status_code{instance=\"http://angulosolido.pt/\",job=\"blackbox\",module=\"http_2xx\"}\t"
      }
     ]
    },
    {
     "title": "Average Probe Duration",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=\"http://angulosolido.pt/\",job=\"blackbox\",module=\"http_2xx\"})"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_dns_lookup_time_seconds{instance=\"http://angulosolido.pt/\",job=\"blackbox\",module=\"http_2xx\"}\t)"
      }
     ]
    }
   ]
  }
 ]
}